import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/header';
import Footer from '../components/footer';
import Description from '../components/description';
import { useEffect, useState } from 'react';

export default function Home() {
  // State
  const [walletAddress, setWalletAddress] = useState('');

  // check if wallet is available
  const checkIfWalletIsAvailable = async () => {
    try {
      const { solana } = window;
      if (solana) {
        console.log('Wallet is available');
        // connecting to user wallet with solana.connect
        const res = await solana.connect({ onlyIfTrusted: true });
        //set the user wallet address
        setWalletAddress(res.publicKey.toString());
      } else {
        Alert('Get a Phantom Wallet');
      }
    } catch (error) {
      console.error(error);
    }
  };

  const connectWallet = async () => {
    try {
      const { solana } = window;
      if (solana) {
        const res = await solana.connect({ onlyIfTrusted: true });
        setWalletAddress(res.publicKey.toString());
      }
    } catch (error) {
      console.error(error);
    }
  };

  const NotConnectedButton = () => (
    <button
      className={[styles.cta_button, styles.connect_wallet_button].join(' ')}
      onClick={connectWallet}
    >
      Connect to Wallet
    </button>
  );

  // when the page loads, check if wallet is available
  useEffect(() => {
    window.addEventListener('load', async (event) => {
      await checkIfWalletIsAvailable();
    });
  }, []);

  return (
    <div className={styles.app}>
      <Head>
        <title>Just Gifs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={walletAddress ? styles.container : styles.authed_container}
      >
        <div className={styles.container}>
          <Header />
          <Description />
          {!walletAddress && NotConnectedButton()}
        </div>
        <Footer />
      </div>
    </div>
  );
}
