/* eslint-disable @next/next/no-img-element */
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/header';
import Footer from '../components/footer';
import Description from '../components/description';
import { useEffect, useState } from 'react';

const TEST_GIFs = [
  'https://i.giphy.com/media/eIG0HfouRQJQr1wBzz/giphy.webp',
  'https://media3.giphy.com/media/L71a8LW2UrKwPaWNYM/giphy.gif?cid=ecf05e47rr9qizx2msjucl1xyvuu47d7kf25tqt2lvo024uo&rid=giphy.gif&ct=g',
  'https://media4.giphy.com/media/AeFmQjHMtEySooOc8K/giphy.gif?cid=ecf05e47qdzhdma2y3ugn32lkgi972z9mpfzocjj6z1ro4ec&rid=giphy.gif&ct=g',
  'https://i.giphy.com/media/PAqjdPkJLDsmBRSYUp/giphy.webp',
];

export default function Home() {
  // State
  const [walletAddress, setWalletAddress] = useState('');

  // check if wallet is available
  const checkIfWalletIsAvailable = async () => {
    try {
      const { solana } = window;
      if (solana) {
        console.log('Wallet is available');
        // connecting to user wallet with solana.connect
        const res = await solana.connect();
        //set the user wallet address
        setWalletAddress(res.publicKey.toString());
      } else {
        alert('Get a Phantom Wallet');
      }
    } catch (error) {
      console.error(error);
    }
  };

  const connectWallet = async () => {
    try {
      const { solana } = window;
      if (solana) {
        const res = await solana.connect();
        setWalletAddress(res.publicKey.toString());
      }
    } catch (error) {
      console.error(error);
    }
  };

  const NotConnectedButton = () => (
    <button
      className={[styles.cta_button, styles.connect_wallet_button].join(' ')}
      onClick={connectWallet}
    >
      Connect to Wallet
    </button>
  );

  const renderGIFContainer = () => (
    <div className={styles.connected_container}>
      <div className={styles.gif_grid}>
        {TEST_GIFs.map((gif) => (
          <div className={styles.gif_item} key={gif}>
            <img src={gif} alt={gif} />
          </div>
        ))}
      </div>
    </div>
  );

  // when the page loads, check if wallet is available
  useEffect(() => {
    window.addEventListener('load', async (event) => {
      await checkIfWalletIsAvailable();
    });
  }, []);

  return (
    <div className={styles.app}>
      <Head>
        <title>Just GIFs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={walletAddress ? styles.container : styles.authed_container}
      >
        <div className={styles.container}>
          <Header />
          <Description />
          {!walletAddress && NotConnectedButton()}
          {walletAddress && renderGIFContainer()}
        </div>
        <Footer />
      </div>
    </div>
  );
}
